name: Consolidated CI, Build, and Deploy Application

on:
  workflow_call:
    inputs:
      repository:
        description: "Nome do repositório (ex: account, auth, etc.) - usado para nomear artefatos e encontrar manifestos."
        required: true
        type: string
      environment:
        description: "Ambiente de deploy (dev, stg, hml, prod)"
        required: true
        type: string
      project_name:
        description: "Nome do projeto"
        required: true
        type: string
      image_repository:
        description: "Repositório de imagens ghcr"
        required: true
        type: string
      dotnet-version:
        description: "Versão do .NET a ser utilizada"
        required: false
        default: '8.0.x'
        type: string
      path_dockerfile:
        description: "Caminho para o Dockerfile (padrão: ./)"
        required: false
        type: string
    secrets:
      GH_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      docker_image_with_tag: ghcr.io/${{ inputs.image_repository }}:${{ github.sha }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build Container Image
        env:
          PATH_DOCKERFILE_INPUT: ${{ inputs.path_dockerfile }}
        run: |
          if [[ -n "$PATH_DOCKERFILE_INPUT" ]]; then
            DOCKERFILE_PATH="$PATH_DOCKERFILE_INPUT"
          else
            DOCKERFILE_PATH="src/${{ inputs.project_name }}/Dockerfile"
          fi

          echo "Dockerfile: $DOCKERFILE_PATH"
          docker build -f "$DOCKERFILE_PATH" \
            -t ghcr.io/${{ inputs.image_repository }}:${{ github.sha }} \
            --build-arg PACKAGE_VERSION=1.0 \
            --build-arg GITHUB_TOKEN=${{ secrets.GH_TOKEN }} \
            --build-arg ENTERPRISE_GITHUB_TOKEN=${{ secrets.GH_TOKEN }} \
            --build-arg ASSEMBLY_VERSION=${{ github.sha }} .

          docker push ghcr.io/${{ inputs.image_repository }}:${{ github.sha }}

  deploy-gitops:
    runs-on: ubuntu-latest
    needs: [build]
    if: always() && needs.build.result == 'success'
    steps:
      - name: Clone GitOps repository
        env:
          GITOPS_REPO_TOKEN: ${{ secrets.GH_TOKEN }}
          GITOPS_REPO_URL: "github.com/providerocp/gitops-apps.git"
          TARGET_GITOPS_DIR: "gitops_repo_checkout"
        run: |
          if [ -z "$GITOPS_REPO_TOKEN" ]; then echo "::error::Secret GH_TOKEN not set."; exit 1; fi
          git clone "https://x-access-token:$GITOPS_REPO_TOKEN@$GITOPS_REPO_URL" "$TARGET_GITOPS_DIR"
          cd "$TARGET_GITOPS_DIR"

      - name: Set Image Tag for GitOps
        id: set_image_env_var
        run: |
          IMAGE_TO_DEPLOY="${{ needs.build.outputs.docker_image_with_tag }}"
          echo "Image to deploy in GitOps: $IMAGE_TO_DEPLOY"
          IMAGE_TAG_ONLY=$(echo "$IMAGE_TO_DEPLOY" | cut -d':' -f2)
          echo "IMAGE_TAG_FOR_GITOPS_UPDATE=$IMAGE_TAG_ONLY" >> $GITHUB_ENV

      - name: Update image tag in GitOps repo
        env:
          TARGET_GITOPS_DIR: "gitops_repo_checkout"
        run: |
          cd "$TARGET_GITOPS_DIR"
          APP_MANIFEST_FILE="aws/apps/overlay/${{ inputs.environment }}/bm-${{ inputs.repository }}/app.yaml"
          if [ ! -f "$APP_MANIFEST_FILE" ]; then echo "::error::Manifest $APP_MANIFEST_FILE not found."; exit 1; fi
          sed -i -E "s#(${{ inputs.image_repository }}:)([^ ]+)#\1$IMAGE_TAG_FOR_GITOPS_UPDATE#" "$APP_MANIFEST_FILE"
          echo "Image tag updated in '$APP_MANIFEST_FILE'."
          git diff "$APP_MANIFEST_FILE"
          cat "$APP_MANIFEST_FILE"
          echo "$IMAGE_TAG_FOR_GITOPS_UPDATE"

      - name: Configure Git for GitOps repo
        env:
          TARGET_GITOPS_DIR: "gitops_repo_checkout"
        run: |
          cd "$TARGET_GITOPS_DIR"
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit changes in GitOps repo
        env:
          TARGET_GITOPS_DIR: "gitops_repo_checkout"
        run: |
          cd "$TARGET_GITOPS_DIR"
          APP_MANIFEST_FILE_RELATIVE_PATH="aws/apps/overlay/${{ inputs.environment }}/bm-${{ inputs.repository }}/app.yaml"
          git add "$APP_MANIFEST_FILE_RELATIVE_PATH"
          if git diff --staged --quiet; then
            echo "No changes to commit in GitOps repo."
          else
            COMMIT_MSG="Update image for bm-${{ inputs.repository }} to $IMAGE_TAG_FOR_GITOPS_UPDATE in ${{ inputs.environment }}"
            git commit -m "$COMMIT_MSG"
          fi

      - name: Push changes to GitOps repo
        env:
          TARGET_GITOPS_DIR: "gitops_repo_checkout"
        run: |
          cd "$TARGET_GITOPS_DIR"
          if [ "$(git rev-list --count @{u}..HEAD)" -gt 0 ]; then
             echo "Pushing changes to GitOps repository..."
             git push
          else
             echo "No new commits to push to GitOps repository."
          fi
