name: Test Application

on:
  workflow_call:
    inputs:
      test:
        description: "Executar testes unitários? (true/false)"
        required: false
        default: false
        type: boolean
      dotnet-version:
        description: "Versão do .NET a ser utilizada"
        required: false
        default: '6.0.x'
        type: string
      sonarqube:
        description: "Analisa o projeto no SonarQube"
        required: false
        type: boolean
        default: false        
    secrets:
      GH_TOKEN:
        required: true

jobs:
  test:
    if: ${{ inputs.test == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install .NET ${{ inputs.dotnet-version || '6.0.x' }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version || '6.0.x' }}
          source-url: https://nuget.pkg.github.com/pipabingomaker/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore --no-incremental

  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    if: inputs.sonarqube == 'true'
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.PROVIDER_SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.PROVIDER_SONAR_URL }}
        with:
          args: >
            -Dsonar.projectKey=${{ inputs.project_name }}
            -Dsonar.projectName=${{ inputs.project_name }}
            -Dsonar.sources=.
            -Dsonar.cs.opencover.reportsPaths=**/coverage.opencover.xml        
