name: Test Application

on:
  workflow_call:
    inputs:
      test:
        description: "Executar testes unitários? (true/false)"
        required: false
        default: false
        type: boolean
      dotnet-version:
        description: "Versão do .NET a ser utilizada"
        required: false
        default: '6.0.x'
        type: string
    secrets:
      GH_TOKEN:
        required: true

jobs:
  test:
    if: ${{ inputs.test == true }}
    runs-on: ubuntu-latest

    services:
      sql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: yourStrong(!)Password
        ports:
          - 1433
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000
          - 10001:10001
          - 10002:10002
              
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install .NET ${{ inputs.dotnet-version || '6.0.x' }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version || '6.0.x' }}
          source-url: https://nuget.pkg.github.com/pipabingomaker/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore --no-incremental
